version: 2.1

commands:
  test-nodejs:
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
jobs:
  node-v14:
    docker:
      - image: node:14
    steps:
      - test-nodejs

workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v14
